### ISSUE TITLE
OpenSSL v1.1 support (was: boost version confusion)

### ISSUE THREAD

**Issue by molecular** [aurarad/Auroracoin#12]
I fail to build auroracoin on an arch linux system.

My system boost libs/headers are version 1.65.1-2

https://github.com/aurarad/Auroracoin/blob/master/doc/build-unix.md says that boost is a dependency but doesn't specify the verision. The first error is:

```
bignum.h:56:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
```

Since the ubuntu section in build-unix says to install boost 1.55, I built and installed boost 1.55 to a separate location which I passed in via `./configure --with-boost=my_155_boost_dir`. Unfortunately also with 1.55 I'm getting many errors related to bignum stuff. At least the first one is the same I posted above, not sure about the other ones, it's loads and loads of errors.

**Which boost version does this actually build with?**

(I tried master and develop branches)

**Comment by BioMike** [comment]
The documentation is not completely up to date, but in this regard it should not matter, as it does not list a specific version. My systems are currently at boost 1.63, and those work. What makes you so sure that this problem is related to boost?

I've looked a bit further and it seems to be related to openssl version 1.1 and up. Could you check and see if you can build against the openssl 1.0 branch?

Refs:
https://groestlcoin.org/forum/index.php?topic=535.0
https://www.openssl.org/docs/man1.1.0/crypto/BN_new.html

If this is the case, this bug should be updated to implement building against openssl v1.1 and up.

**Comment by BioMike** [comment]
Could you give the full error message for reference?

Nevermind.

Possible fixes (some need some clean up):
https://github.com/zcoinofficial/zcoin/pull/111
https://github.com/peercoin/peercoin/commit/5b09830e5de0f5105534e69dbf4acffb3255869b

**Comment by molecular** [comment]
I think I *am* building against openssl-1.0. This is how I do it:

```
export PKG_CONFIG_PATH="/usr/lib/openssl-1.0/pkgconfig"
export CXXFLAGS+=" -I/usr/include/openssl-1.0"
export LDFLAGS+=" -L/usr/lib/openssl-1.0 -lssl"
export CXXFLAGS+=" -fpic"

./autogen.sh
./configure
make -j4
```

maybe the way I do it is not effective?

EDIT: what the... I just re-executed the above and it builds now for some reason. Confused ;|

**Comment by BioMike** [comment]
Always make clean before rebuilding. Sometimes make does not detect changes in the build environment, so it is better to start clean. You also not need to call autogen.sh every time.

**Comment by BioMike** [comment]
Openssl v1.1 support should now be in with commit 2ba591f. I've put it in, in such way that both Openssl branches 1.0 and 1.1 are supported. Do note that I haven't tested a v1.1 build (it builds, but haven't tested the build at runtime), so backup your wallet and perform small transactions initially, just to be sure.
